input_folder: /vols/cms/dmw25/HiggsDNA/output/setting_up_2024
output_path: /vols/cms/dmw25/TIDAL/Draw/plots/setting_up_2024
channels: [tt]
eras: [Run3_2024]
parameter_path: /vols/cms/dmw25/HiggsDNA/scripts/ditau/config
schemes: [stats-check]
run_systematics: false

stats-check:

  systematics:
    per_era:
      default:
        tt:
         - [ "systematic_Trigger", "CMS_HIG25012_trig_*obj_*trigger_*group" ]

        mt:
        - [ "systematic_Tau_EnergyScale_PNet_MUSCALE", "CMS_HIG25012_scale_t_muFake_*group_*year" ]
        - [ "systematic_Muon_ID_iso", "CMS_eff_m_*kind" ]
        - [ "systematic_Tau_FakeRate_mu", "CMS_fake_t_DeepTau2018v2p5_VSmu_*year_eta_*eta"]
        - [ "systematic_Trigger", "CMS_HIG25012_eff_m_trigger"]
        - [ 'systematic_IP_Significance', "CMS_HIG25012_eff_IPSigCut_*obj_eta_*eta"]

        et:
        - [ "systematic_Tau_EnergyScale_PNet_ESCALE", "CMS_HIG25012_scale_t_eFake_*group_*year" ]
        - [ "systematic_Tau_FakeRate_e", "CMS_fake_t_DeepTau2018v2p5_VSe_*year_eta_*eta_*group"]
        - [ "systematic_Electron_Scale_Smearing", "CMS_*kind_e"]
        - [ "systematic_Electron_ID_Reco", "CMS_eff_e_*kind"]
        - [ 'systematic_IP_Significance', "CMS_HIG25012_eff_IPSigCut_*obj_eta_*eta"]
        - [ "systematic_Trigger", "CMS_HIG25012_eff_e_trigger"]

        common:
         - [ "systematic_Fake_Factors", "CMS_HIG25012_fake_t"]
         - [ "systematic_DY_Shape", "CMS_HIG25012_Z_pt_reweighting" ]
         - [ "systematic_TTbar_Shape", "top_pt_reweighting" ]
         - [ "systematic_Tau_ID_PNet", "CMS_HIG25012_eff_t_DeepTau2018v2p5_VSjet_*group"]
         - [ "systematic_Tau_EnergyScale_PNet_TSCALE", "CMS_HIG25012_scale_t_*group_*year" ]
         - [ "systematic_MET_Recoil", "CMS_HIG25012_*type_met" ]
         - [ "systematic_Jet_EnergyScale_Regrouped", "CMS_scale_j_*type" ]
         - [ "systematic_Jet_EnergyResolution", "CMS_res_j_*year" ]
         - [ 'systematic_Pileup', 'CMS_pileup']
         - [ "systematic_IP_Calibration", "CMS_HIG25012_res_IP"]
         - [ "systematic_SV_Resolution", "CMS_HIG25012_res_SV"]
         - [ "systematic_Signal_Theory", "*type_signal"]


  variable_definitions:
      MVA_score: "BDT_pred_score[0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0]"

  tt:
    # Nominal plots (change filtered DY to false if running 2024)
     - { method: '3', category:  ['mva_higgs'], plotting_variable: [ MVA_score], blind: true, use_filtered_DY: false}

  mt:
    # Nominal plots
     - { method: '6', category:  ['mva_higgs'], plotting_variable: [ MVA_score], blind: true, use_filtered_DY: false, additional_selections: ["(mt_1<65)"]}

  et:
    # Nominal plots
     - { method: '6', category:  ['mva_higgs'], plotting_variable: [ MVA_score], blind: true, use_filtered_DY: false, additional_selections: ["(mt_1<65)"]}
  
